export const DESTINATIONS = [
  { key: "kz", name: "Qozog'iston", x: 615, y: 185, delay: 0.10 },
  { key: "ru", name: "Rossiya", x: 450, y: 140, delay: 0.20 },
  { key: "de", name: "Germaniya", x: 380, y: 160, delay: 0.40 },
  { key: "cn", name: "Xitoy", x: 740, y: 200, delay: 0.30 },
  { key: "sa", name: "Saudiya Arabistoni", x: 490, y: 262, delay: 0.50 },
  { key: "ae", name: "BAA", x: 522, y: 272, delay: 0.60 },
  { key: "kr", name: "Janubiy Koreya", x: 810, y: 205, delay: 0.70 },
  { key: "us", name: "AQSh", x: 180, y: 180, delay: 0.90 },
  { key: "kg", name: "Qirg'iziston", x: 604, y: 202, delay: 0.15 },
  { key: "tj", name: "Tojikiston", x: 592, y: 222, delay: 0.18 },
  { key: "tm", name: "Turkmaniston", x: 546, y: 228, delay: 0.22 },
  { key: "af", name: "Afg'oniston", x: 574, y: 238, delay: 0.26 },
  { key: "mn", name: "Mongoliya", x: 700, y: 162, delay: 0.34 },
  { key: "az", name: "Ozarbayjon", x: 506, y: 206, delay: 0.44 },
  { key: "ge", name: "Gruziya", x: 490, y: 196, delay: 0.48 },
  { key: "am", name: "Armaniston", x: 497, y: 204, delay: 0.52 },
  { key: "jo", name: "Iordaniya", x: 466, y: 248, delay: 0.56 }
];

export const CONTINENTS = [
  // Eurasia
  [[335,225],[338,170],[360,135],[410,112],[490,96],[600,90],[700,98],[800,110],[862,138],[872,178],[840,205],[805,238],[765,268],[725,252],[685,262],[645,242],[605,252],[565,242],[525,232],[485,242],[445,232],[402,222],[362,236]],
  // Arabian peninsula
  [[452,242],[500,236],[532,256],[537,290],[500,316],[464,290]],
  // India
  [[586,248],[622,248],[616,300],[600,322],[583,290]],
  // SE Asia
  [[648,258],[692,254],[702,290],[668,302]],
  // North America
  [[88,132],[160,104],[242,110],[282,140],[272,182],[232,212],[200,252],[168,262],[138,220],[98,182]],
  // Africa (north half, context)
  [[378,252],[440,246],[470,272],[458,332],[428,382],[398,390],[374,330],[368,280]],
  // British Isles
  [[348,134],[362,130],[366,146],[350,150]]
];

export const I18N = {
  uz: {
    dir: "ltr",
    nav_about: "Kompaniya", nav_products: "Mahsulotlar", nav_production: "Ishlab chiqarish",
    nav_export: "Eksport", nav_certs: "Sertifikatlar", nav_coop: "Hamkorlik",
    nav_jobs: "Vakansiyalar", nav_news: "Yangiliklar", nav_contact: "Aloqa",
    btn_catalog: "Katalog",
    hero_kicker: "1998 yildan beri",
    hero_title: "Markaziy Osiyoning yetakchi konditer fabrikalaridan biri",
    hero_sub: "1998 yildan buyon 100+ turdagi shirinlik ishlab chiqaramiz va 15+ mamlakatga eksport qilamiz.",
    hero_cta1: "Katalog yuklab olish", hero_cta2: "Hamkorlik", hero_watch: "Videoni ko'rish",
    about_kicker: "Kompaniya haqida",
    about_title: "Bozor rastasidan xalqaro fabrikagacha",
    about_text: "1998 yilda kichik sexdan boshlangan yo'l bugun ikki zamonaviy fabrika, 100 dan ortiq mahsulot turi va 15+ davlatga eksportga aylandi. Biz har bir mahsulotda sifat, halollik va shirin bolalik ta'mini saqlaymiz.",
    about_btn: "Batafsil",
    stat_exp: "yillik tajriba", stat_clients: "mamnun mijoz", stat_products: "mahsulot turi", stat_countries: "eksport davlati",
    prod_kicker: "Mahsulotlar", prod_title: "Sevimli ta'mlar katalogi", prod_sub: "Tabiiy xomashyo va zamonaviy texnologiya uyg'unligida tayyorlangan 100+ turdagi shirinliklar.", prod_all: "Barcha mahsulotlar (100+) →",
    chip_all: "Hammasi", chip_cookie: "Pechenye", chip_wafer: "Vafli", chip_choco: "Shokoladli konfetlar",
    production_kicker: "Ishlab chiqarish", production_title: "Zamonaviy texnologiya, an'anaviy ta'm",
    production_sub: "Nuqtalar ustiga keling — jarayon bilan tanishing",
    hs1_t: "Xomashyo nazorati", hs1_d: "Har bir partiya laboratoriyada tekshiriladi",
    hs2_t: "Avtomatlashtirilgan liniyalar", hs2_d: "Yevropa uskunalarida uzluksiz ishlab chiqarish",
    hs3_t: "Sifat nazorati", hs3_d: "HACCP tizimi bo'yicha 3 bosqichli nazorat",
    hs4_t: "Qadoqlash", hs4_d: "Eksport talablariga mos zamonaviy qadoq",
    export_kicker: "Eksport geografiyasi", export_title: "Toshkentdan — dunyoga",
    export_sub: "15+ mamlakatdagi distribyutorlar SFAD mahsulotlariga ishonadi", export_t1: "Dunyoning", export_hl: "15+ davlatida", export_t2: "",
    certs_kicker: "Sifat kafolati", certs_title: "Xalqaro sertifikatlar",
    certs_sub: "ISO 22000, HALAL va HACCP — har bir mahsulot xalqaro talablarga javob beradi",
    coop_title: "Distribyutor bo'ling", coop_text: "Eksport bo'limimiz 24 soat ichida siz bilan bog'lanadi. Narxlar, logistika va shaxsiy shartlar — bitta arizada.",
    form_name: "Ismingiz", form_phone: "Telefon", form_company: "Kompaniya / davlat", form_msg: "Xabar", form_send: "Ariza yuborish",
    jobs_title: "SFAD jamoasiga qo'shiling", jobs_text: "O'sib borayotgan fabrikamizga g'ayratli mutaxassislar kerak. Arizangizni qoldiring — HR jamoamiz bog'lanadi.",
    form_role: "Yo'nalish / izoh",
    news_kicker: "Yangiliklar", news_title: "SFAD hayotidan",
    news_1: "15+ mamlakatga eksport: SFAD qanday chiqdi",
    news_2: "Bozor rastasidan ikki fabrikagacha: SFAD tarixi",
    news_3: "Yangi mahsulot: Choko Joke",
    news_more: "O'qish",
    contact_kicker: "Aloqa", contact_title: "Biz bilan bog'laning",
    contact_addr: "Shirok ko'chasi 100, Olmazor tumani, Toshkent 100057",
    footer_tag: "Shirinliklar sehri — 1998 yildan buyon",
    footer_nav: "Bo'limlar", footer_contact: "Kontaktlar",
    footer_rights: "© 2026 SFAD. Barcha huquqlar himoyalangan."
  },
  ru: {
    dir: "ltr",
    nav_about: "Компания", nav_products: "Продукция", nav_production: "Производство",
    nav_export: "Экспорт", nav_certs: "Сертификаты", nav_coop: "Партнёрство",
    nav_jobs: "Вакансии", nav_news: "Новости", nav_contact: "Контакты",
    btn_catalog: "Каталог",
    hero_kicker: "С 1998 года",
    hero_title: "Одна из ведущих кондитерских фабрик Центральной Азии",
    hero_sub: "С 1998 года выпускаем 100+ видов сладостей и экспортируем в 15+ стран.",
    hero_cta1: "Скачать каталог", hero_cta2: "Партнёрство", hero_watch: "Смотреть видео",
    about_kicker: "О компании",
    about_title: "От рыночного прилавка до международной фабрики",
    about_text: "Путь, начавшийся в 1998 году с небольшого цеха, сегодня — это две современные фабрики, более 100 видов продукции и экспорт в 15+ стран. В каждом продукте мы сохраняем качество, честность и вкус детства.",
    about_btn: "Подробнее",
    stat_exp: "лет опыта", stat_clients: "довольных клиентов", stat_products: "видов продукции", stat_countries: "стран экспорта",
    prod_kicker: "Продукция", prod_title: "Каталог любимых вкусов", prod_sub: "100+ видов сладостей, созданных на стыке натурального сырья и современных технологий.", prod_all: "Вся продукция (100+) →",
    chip_all: "Все", chip_cookie: "Печенье", chip_wafer: "Вафли", chip_choco: "Шоколадные конфеты",
    production_kicker: "Производство", production_title: "Современные технологии, традиционный вкус",
    production_sub: "Наведите на точки — узнайте о процессе",
    hs1_t: "Контроль сырья", hs1_d: "Каждая партия проверяется в лаборатории",
    hs2_t: "Автоматизированные линии", hs2_d: "Непрерывное производство на европейском оборудовании",
    hs3_t: "Контроль качества", hs3_d: "3-ступенчатый контроль по системе HACCP",
    hs4_t: "Упаковка", hs4_d: "Современная упаковка по экспортным требованиям",
    export_kicker: "География экспорта", export_title: "Из Ташкента — в мир",
    export_sub: "Дистрибьюторы в 15+ странах доверяют продукции SFAD", export_t1: "В", export_hl: "15+ странах", export_t2: "мира",
    certs_kicker: "Гарантия качества", certs_title: "Международные сертификаты",
    certs_sub: "ISO 22000, HALAL и HACCP — каждый продукт отвечает международным требованиям",
    coop_title: "Станьте дистрибьютором", coop_text: "Наш экспортный отдел свяжется с вами в течение 24 часов. Цены, логистика и индивидуальные условия — в одной заявке.",
    form_name: "Ваше имя", form_phone: "Телефон", form_company: "Компания / страна", form_msg: "Сообщение", form_send: "Отправить заявку",
    jobs_title: "Присоединяйтесь к команде SFAD", jobs_text: "Растущей фабрике нужны энергичные специалисты. Оставьте заявку — HR-команда свяжется с вами.",
    form_role: "Направление / комментарий",
    news_kicker: "Новости", news_title: "Из жизни SFAD",
    news_1: "Экспорт в 15+ стран: как SFAD вышел на рынки",
    news_2: "От рыночного прилавка до двух фабрик: история SFAD",
    news_3: "Новый продукт: Choko Joke",
    news_more: "Читать",
    contact_kicker: "Контакты", contact_title: "Свяжитесь с нами",
    contact_addr: "ул. Широк 100, Алмазарский район, Ташкент 100057",
    footer_tag: "Магия сладостей — с 1998 года",
    footer_nav: "Разделы", footer_contact: "Контакты",
    footer_rights: "© 2026 SFAD. Все права защищены."
  },
  en: {
    dir: "ltr",
    nav_about: "Company", nav_products: "Products", nav_production: "Production",
    nav_export: "Export", nav_certs: "Certificates", nav_coop: "Partnership",
    nav_jobs: "Careers", nav_news: "News", nav_contact: "Contact",
    btn_catalog: "Catalog",
    hero_kicker: "Since 1998",
    hero_title: "One of Central Asia's leading confectionery factories",
    hero_sub: "Since 1998 we have made 100+ kinds of sweets and export to 15+ countries.",
    hero_cta1: "Download catalog", hero_cta2: "Partnership", hero_watch: "Watch video",
    about_kicker: "About the company",
    about_title: "From a market stall to an international factory",
    about_text: "A journey that began in 1998 with a small workshop is today two modern factories, 100+ product lines and export to 15+ countries. In every product we preserve quality, integrity and the sweet taste of childhood.",
    about_btn: "Learn more",
    stat_exp: "years of experience", stat_clients: "happy customers", stat_products: "product lines", stat_countries: "export countries",
    prod_kicker: "Products", prod_title: "A catalog of favorite flavors", prod_sub: "100+ kinds of sweets, made where natural ingredients meet modern technology.", prod_all: "All products (100+) →",
    chip_all: "All", chip_cookie: "Cookies", chip_wafer: "Wafers", chip_choco: "Chocolate candies",
    production_kicker: "Production", production_title: "Modern technology, traditional taste",
    production_sub: "Hover the dots to explore the process",
    hs1_t: "Raw material control", hs1_d: "Every batch is lab-tested",
    hs2_t: "Automated lines", hs2_d: "Continuous production on European equipment",
    hs3_t: "Quality control", hs3_d: "3-stage control under the HACCP system",
    hs4_t: "Packaging", hs4_d: "Modern packaging built for export",
    export_kicker: "Export geography", export_title: "From Tashkent — to the world",
    export_sub: "Distributors in 15+ countries trust SFAD products", export_t1: "In", export_hl: "15+ countries", export_t2: "worldwide",
    certs_kicker: "Quality guarantee", certs_title: "International certificates",
    certs_sub: "ISO 22000, HALAL and HACCP — every product meets international requirements",
    coop_title: "Become a distributor", coop_text: "Our export team will contact you within 24 hours. Pricing, logistics and personal terms — in one application.",
    form_name: "Your name", form_phone: "Phone", form_company: "Company / country", form_msg: "Message", form_send: "Send application",
    jobs_title: "Join the SFAD team", jobs_text: "Our growing factory needs driven specialists. Leave an application — our HR team will reach out.",
    form_role: "Position / comment",
    news_kicker: "News", news_title: "Life at SFAD",
    news_1: "Exporting to 15+ countries: how SFAD did it",
    news_2: "From a market stall to two factories: the SFAD story",
    news_3: "New product: Choko Joke",
    news_more: "Read",
    contact_kicker: "Contact", contact_title: "Get in touch",
    contact_addr: "100 Shirok street, Olmazor district, Tashkent 100057",
    footer_tag: "The magic of sweets — since 1998",
    footer_nav: "Sections", footer_contact: "Contacts",
    footer_rights: "© 2026 SFAD. All rights reserved."
  },
  ar: {
    dir: "rtl",
    nav_about: "الشركة", nav_products: "المنتجات", nav_production: "الإنتاج",
    nav_export: "التصدير", nav_certs: "الشهادات", nav_coop: "الشراكة",
    nav_jobs: "الوظائف", nav_news: "الأخبار", nav_contact: "اتصل بنا",
    btn_catalog: "الكتالوج",
    hero_kicker: "منذ عام 1998",
    hero_title: "واحدة من أبرز مصانع الحلويات في آسيا الوسطى",
    hero_sub: "منذ عام 1998 ننتج أكثر من 100 نوع من الحلويات ونصدّر إلى أكثر من 15 دولة.",
    hero_cta1: "تحميل الكتالوج", hero_cta2: "الشراكة", hero_watch: "شاهد الفيديو",
    about_kicker: "عن الشركة",
    about_title: "من بسطة السوق إلى مصنع دولي",
    about_text: "رحلة بدأت عام 1998 بورشة صغيرة أصبحت اليوم مصنعين حديثين وأكثر من 100 منتج وتصديراً إلى أكثر من 15 دولة. في كل منتج نحافظ على الجودة والأمانة وطعم الطفولة الحلو.",
    about_btn: "المزيد",
    stat_exp: "سنة من الخبرة", stat_clients: "عميل سعيد", stat_products: "نوع منتج", stat_countries: "دولة تصدير",
    prod_kicker: "المنتجات", prod_title: "كتالوج النكهات المفضلة", prod_sub: "أكثر من 100 نوع من الحلويات صُنعت حيث تلتقي المكونات الطبيعية بالتقنية الحديثة.", prod_all: "كل المنتجات (100+) ←",
    chip_all: "الكل", chip_cookie: "بسكويت", chip_wafer: "ويفر", chip_choco: "شوكولاتة",
    production_kicker: "الإنتاج", production_title: "تقنية حديثة، طعم أصيل",
    production_sub: "مرر فوق النقاط لاستكشاف العملية",
    hs1_t: "مراقبة المواد الخام", hs1_d: "تُفحص كل دفعة في المختبر",
    hs2_t: "خطوط أوتوماتيكية", hs2_d: "إنتاج مستمر على معدات أوروبية",
    hs3_t: "مراقبة الجودة", hs3_d: "مراقبة من 3 مراحل وفق نظام HACCP",
    hs4_t: "التغليف", hs4_d: "تغليف حديث وفق متطلبات التصدير",
    export_kicker: "جغرافيا التصدير", export_title: "من طشقند — إلى العالم",
    export_sub: "موزعون في أكثر من 15 دولة يثقون بمنتجات SFAD", export_t1: "في", export_hl: "أكثر من 15 دولة", export_t2: "حول العالم",
    certs_kicker: "ضمان الجودة", certs_title: "شهادات دولية",
    certs_sub: "ISO 22000 وHALAL وHACCP — كل منتج يلبي المتطلبات الدولية",
    coop_title: "كن موزعاً", coop_text: "سيتواصل معك قسم التصدير خلال 24 ساعة. الأسعار واللوجستيات والشروط الخاصة — في طلب واحد.",
    form_name: "اسمك", form_phone: "الهاتف", form_company: "الشركة / الدولة", form_msg: "الرسالة", form_send: "إرسال الطلب",
    jobs_title: "انضم إلى فريق SFAD", jobs_text: "مصنعنا المتنامي يحتاج إلى متخصصين طموحين. اترك طلبك وسيتواصل معك فريق الموارد البشرية.",
    form_role: "التخصص / تعليق",
    news_kicker: "الأخبار", news_title: "من حياة SFAD",
    news_1: "التصدير إلى أكثر من 15 دولة: كيف نجحت SFAD",
    news_2: "من بسطة السوق إلى مصنعين: قصة SFAD",
    news_3: "منتج جديد: Choko Joke",
    news_more: "اقرأ",
    contact_kicker: "اتصل بنا", contact_title: "تواصل معنا",
    contact_addr: "شارع شيروك 100، حي ألمازار، طشقند 100057",
    footer_tag: "سحر الحلويات — منذ 1998",
    footer_nav: "الأقسام", footer_contact: "جهات الاتصال",
    footer_rights: "© 2026 SFAD. جميع الحقوق محفوظة."
  }
};

export const TASHKENT = { x: 669.3, y: 335.6 };
export const MAP_PARTNERS = [
  { id:"KZ", name:"Qozog'iston",        flag:"🇰🇿", x:690.7, y:328.2 },
  { id:"KG", name:"Qirg'iziston",       flag:"🇰🇬", x:684.3, y:329.7 },
  { id:"TJ", name:"Tojikiston",         flag:"🇹🇯", x:668.0, y:345.6 },
  { id:"TM", name:"Turkmaniston",       flag:"🇹🇲", x:638.7, y:347.8 },
  { id:"AF", name:"Afg'oniston",        flag:"🇦🇫", x:669.0, y:359.7 },
  { id:"RU", name:"Rossiya",            flag:"🇷🇺", x:580.5, y:273.9 },
  { id:"CN", name:"Xitoy",              flag:"🇨🇳", x:801.7, y:340.8 },
  { id:"MN", name:"Mongoliya",          flag:"🇲🇳", x:775.0, y:309.6 },
  { id:"KR", name:"Janubiy Koreya",     flag:"🇰🇷", x:831.4, y:349.1 },
  { id:"SA", name:"Saudiya Arabistoni", flag:"🇸🇦", x:605.9, y:391.4 },
  { id:"AE", name:"BAA",                flag:"🇦🇪", x:630.0, y:389.8 },
  { id:"JO", name:"Iordaniya",          flag:"🇯🇴", x:575.7, y:368.3 },
  { id:"AZ", name:"Ozarbayjon",         flag:"🇦🇿", x:614.8, y:338.9 },
  { id:"AM", name:"Armaniston",         flag:"🇦🇲", x:599.8, y:339.7 },
  { id:"GE", name:"Gruziya",            flag:"🇬🇪", x:600.6, y:334.0 },
  { id:"DE", name:"Germaniya",          flag:"🇩🇪", x:512.4, y:289.3 },
  { id:"US", name:"AQSh",               flag:"🇺🇸", x:267.0, y:337.8 }
];
